package org.feitian.dpc;

public class ApplicationHidden {
    public final static String[] hiddens = {
            /////////////////////////////////// individual apps ////////////////////////////////////
            //chrome web browser
            "com.android.chrome",

            // if google play store is hidden, no app can be installed from apk or google play store.
            // but it has built-in games
//            "com.android.vending", //google play store

            //facebook lite
            "com.facebook.lite",

            //google assistant go
            "com.google.android.apps.assistant",

            //google maps go
            "com.google.android.apps.mapslite",

            //google go
            "com.google.android.apps.searchlite",

            //YouTube Go
            "com.google.android.apps.youtube.mango",

            //gmail
            "com.google.android.gm.lite",

            //google play music
//            "com.google.android.music",

            //youtube
            "com.google.android.youtube",

            //samsung max
            "com.samsung.max.go",

            // builtin video player. got the package name from Clear App Data in DPC.
//            "com.samsung.android.video",

            //camera
//            "com.sec.android.app.camera",

            //samsung apps store
            "com.sec.android.app.samsungapps",

            //samsung internet
            "com.sec.android.app.sbrowser.lite",

            // If we hide this app, camera can take picture but cannot go to the picture from the
            // camera.
//            "com.sec.android.gallery3d",

            "com.google.android.googlequicksearchbox",

            // this is actually for signal. weird name. This app will not be hidden for group
            // leaders. It will be configured using QR code generated by QRCodeAndroidExt in another
            // application.
            "org.thoughtcrime.securesms",

            ///////////////////////////////// prefixes /////////////////////////////////////////////
//            "com.zynga",
//            "com.tripledot",
//            "com.varomoney",
//            "com.pinterest",
//            "net.wooga",
//            "com.superplaystudios",
//            "com.bbumgames",
//            "com.king",
//            "com.squareup",
//            "com.acoms",
//            "com.digitalturbine",
//            "com.asurion",
    };
}
